-- TODO: Rmeove the configuration tables from the list of delete tables
use mydb_testcases;

SET foreign_key_checks = 0;
DELETE FROM ticket_status_link;
DELETE FROM ticket_status;
DELETE FROM route_link;
DELETE FROM route;
DELETE FROM record_field;
DELETE FROM product_link;
DELETE FROM product;
DELETE FROM ticket_class;
DELETE FROM ticket_allocation_code;
DELETE FROM product_type;
DELETE FROM process_control;
DELETE FROM location_link;
DELETE FROM location;
DELETE FROM location_type;
DELETE FROM instance_control_log;
DELETE FROM group_function_type;
DELETE FROM fares_checking_exclusion;
DELETE FROM code_book;
DELETE FROM type;
DELETE FROM calendar;
DELETE FROM week;
DELETE FROM period;
DELETE FROM year;
DELETE FROM business;
DELETE FROM application_parameters;
SET foreign_key_checks = 1;